name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          NEXT_TELEMETRY_DISABLED: "1"
          SENTRY_DSN: ""
          NEXT_PUBLIC_SENTRY_DSN: ""
          SENTRY_ENVIRONMENT: "ci"
          STRIPE_API_VERSION: "2025-07-30.basil"
          STRIPE_SECRET_KEY: "sk_test_dummy"
          NEXTAUTH_SECRET: "dummysecretforci"
      
      - name: Type check
        run: npm run typecheck
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          NEXT_TELEMETRY_DISABLED: "1"
          SENTRY_DSN: ""
          NEXT_PUBLIC_SENTRY_DSN: ""
          SENTRY_ENVIRONMENT: "ci"
          STRIPE_API_VERSION: "2025-07-30.basil"
          STRIPE_SECRET_KEY: "sk_test_dummy"
          NEXTAUTH_SECRET: "dummysecretforci"
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          NEXT_TELEMETRY_DISABLED: "1"
          SENTRY_DSN: ""
          NEXT_PUBLIC_SENTRY_DSN: ""
          SENTRY_ENVIRONMENT: "ci"
          STRIPE_API_VERSION: "2025-07-30.basil"
          STRIPE_SECRET_KEY: "sk_test_dummy"
          NEXTAUTH_SECRET: "dummysecretforci"
      
      - name: Upload build artifacts on error
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: next-trace
          path: .next/trace
          if-no-files-found: ignore