name: Lighthouse CI

on:
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    needs: []
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          INSANYCK_DISABLE_BACKEND: "1"
          PORT: 3000
      
      - name: Start server and run Lighthouse CI
        run: |
          npm run start &
          sleep 10
          npm run lhci:ci
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          INSANYCK_DISABLE_BACKEND: "1"
          PORT: 3000
      
      - name: Upload Lighthouse CI artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-ci-results
          path: .lighthouseci/