name: Lighthouse CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          SENTRY_DSN: ""
          NEXT_PUBLIC_SENTRY_DSN: ""
          SENTRY_ENVIRONMENT: "ci"
          STRIPE_API_VERSION: "2025-07-30.basil"
          STRIPE_SECRET_KEY: "sk_test_dummy"
          NEXTAUTH_SECRET: "dummysecretforci"
      
      - name: Start server
        run: |
          npm run start &
          npx wait-on http://localhost:3000
        env:
          NODE_ENV: production
          NEXT_PUBLIC_URL: http://localhost:3000
          SENTRY_DSN: ""
          NEXT_PUBLIC_SENTRY_DSN: ""
          SENTRY_ENVIRONMENT: "ci"
          STRIPE_API_VERSION: "2025-07-30.basil"
          STRIPE_SECRET_KEY: "sk_test_dummy"
          NEXTAUTH_SECRET: "dummysecretforci"
      
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: ./lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-ci-results
          path: |
            .lighthouseci
            lighthouse-ci-results.html
            lighthouse-ci-results.json